name: Deployment.OneDMS
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# copy delivery from deploy1 to deploy5 to OneDMS Windows SCP Server
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *'

env:
 file_exists: ""


jobs:
  Check-Delivery:
    runs-on: github@de0822yr.dc-ratingen.de
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: pwd
      - run: ssh github@de01c4xr.dc-ratingen.de -T "mkdir -p /opt/home/github/actions-runner/transfer/"
      - run: echo file_exists=$( ssh github@de01c4xr.dc-ratingen.de -T "if test \$(find \"/archive/ONEDMS/vfacc/\" -type f -mtime -1 | wc -c) == \"0\" ; then echo 1 ; else echo 0 ; fi" ) >> $GITHUB_ENV
      - run: echo ${{ env.file_exists }}
    outputs:
      output1: ${{ env.file_exists }}
  Copy-Delivery:
      needs: Check-Delivery
      runs-on: github@de0822yr.dc-ratingen.de
      if: needs.Check-Delivery.outputs.output1 == '0'
      steps:
      - run: ssh github@de01c4xr.dc-ratingen.de -T "for CN in \$( find \"/archive/ONEDMS/vfacc/\" -type f -mtime -1 | grep '\.zip$' | cut -d/ -f5 ) ; do cd /archive/ONEDMS/vfacc/ && zip -r /opt/home/github/actions-runner/transfer/\${CN}.zip \${CN} ; done "
      - run: mkdir -p /opt/home/github/actions-runner/transfer/
      - run: scp -rp github@de01c4xr.dc-ratingen.de:/opt/home/github/actions-runner/transfer/* /opt/home/github/actions-runner/transfer/
      - run: echo "${{ secrets.DEPLOYMENT_ONEDMS }}"
      - run: ssh github@de0822yr.dc-ratingen.de -T 'echo "set timeout 30;
          spawn sftp Deployment.OneDMS@filetransfer-onedms.vodafone.de;
          expect \"password:\" { send \"${{ secrets.DEPLOYMENT_ONEDMS }}\n\" };
          expect \"sftp>\" { send \"ls -l\n\" };
          expect \"sftp>\" { send \"put /opt/home/github/actions-runner/transfer/*\n\" };
          expect \"sftp>\" { send \"ls -l\n\" };
          expect \"sftp>\" { send \"exit\n\"" } | expect'
      - run: ssh github@de01c4xr.dc-ratingen.de -T "rm -rf /opt/home/github/actions-runner/transfer"
      - run: rm -rf /opt/home/github/actions-runner/transfer
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
