name: awsS3Caller

on:
  workflow_dispatch:
  
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/awsS3Reusable.yml
    with:
      terraformPath: ${{ github.repository }}/terraform_s3/*
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
