name: awsS3Reusable

on:
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true     
      aws-session-token: 
        required: true
  
env:
  terraformPath: ${{ inputs.terraformPath }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "terraformPath=${{ github.workspace }}/${terraformPath}" >> $GITHUB_ENV
    - run: echo "terraformPath=${terraformPath}"
    
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Storing manifests in GitHub
      uses: actions/upload-artifact@v3
      with:
       name: terraformArtifacts
       path: ${{ env.terraformPath }}
    outputs: 
      terraformPath: ${{ env.terraformPath }}
        
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: showvar
      env:
        terraformPath: ${{ needs.build.outputs.terraformPath }}
      run: echo "terraformPath=${terraformPath}"
    
    - name: Downloading manifests from GitHub
      uses: actions/download-artifact@v3
      with:
       name: terraformArtifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      env:
        terraformPath: ${{ needs.build.outputs.terraformPath }}
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity
    - name: Execute terraform scripts to launch S3 bucket
      run: |
        terraform init
        terraform apply --auto-approve
