name: awsSSH

on:
  workflow_dispatch:

jobs:
        
  deploy: 
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity
        
    - name: sshpass
      run: |
        sshpass -p${{ secrets.ANSIBLE_USER_PW }} ssh -o StrictHostKeyChecking=no ansiuser@3.222.185.41 mkdir /home/ansiuser/.ssh && chmod 700 /home/ansiuser/.ssh
        ssh-keygen -q -t rsa -f /home/ansiuser/.ssh/id_rsa -N '' <<< $'\ny' >/dev/null 2>&1
        sshpass -p${{ secrets.ANSIBLE_USER_PW }} ssh-copy-id -i $HOME/.ssh/id_rsa.pub ansiuser@3.222.185.41
        sshpass -p${{ secrets.ANSIBLE_USER_PW }} ssh -o StrictHostKeyChecking=no ansiuser@3.222.185.41 ls -l /home/ansiuser/.ssh
