name: awsSSH

on:
  workflow_dispatch:

jobs:
        
  deploy: 
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity
        
    - name: sshpass
      run: sshpass -p${{ secrets.ANSIBLE_USER_PW }} ssh -o StrictHostKeyChecking=no ansiuser@3.222.185.41 pwd && ls -la
    - run: sshpass -p${{ secrets.ANSIBLE_USER_PW }} ssh -o StrictHostKeyChecking=no ansiuser@3.222.185.41 ls -l /home/ansiuser/.ssh
      #run: SSHPASS=${{ secrets.ANSIBLE_USER_PW }} sshpass -e ssh ansiuser@3.222.185.41 ls
      #sshpass -pansiuser ssh -o StrictHostKeyChecking=no ansiuser@172.31.5.131 ls -la
