name: awsTerraformCallerDestroy

on:
  workflow_dispatch:
  
jobs:
  Master:
    uses: ./.github/workflows/awsTerraformReusableDestroy.yml 
    with:
      terraformPath: awsAnsible/*
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        
  Worker:
    uses: ./.github/workflows/awsTerraformReusableDestroy.yml
    needs: Master
    with:
      terraformPath: awsWorkerIAM/*
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        
  s3:
    uses: ./.github/workflows/awsTerraformReusableDestroy.yml
    needs: Worker
    with:
      terraformPath: terraform_s3/*
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
