name: Github Actions test

on: 
  workflow_dispatch:

env:
  ENV_VARIABLE: ok
  VAR1 : job2
  VAR2: ${{ github.event.repository.name }} 
  HOMEDIR: /home
 
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "$ENV_VARIABLE"
        - run: ls -ltr "$HOMEDIR"

    job2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "$VAR1"
        - run: ls -ltr "$HOMEDIR"
    
    job3:
      runs-on: ubuntu-latest
      steps:
        - run: echo "$VAR2"
        - run: ls -ltr "$HOMEDIR"
