name: tf

on:
  workflow_dispatch:
    inputs:
      tf_typ:
        default: apply
        type: choice
        description: deploy or destroy
        options: 
        - apply
        - destroy
  
jobs:
  modules:
    strategy:
      matrix:
        target: [tf_modules/module1/*, tf_modules/module2/*]
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/awsTerraformReusable2.yml
    with:
      terraformPath: ${{ matrix.target }}
      tf_typ: ${{ inputs.tf_typ }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    
