name: tf2caller

on:
  workflow_dispatch:
    inputs:
      tf_typ:
        default: plan
        type: choice
        description: deploy or destroy
        options:
        - apply
        - destroy
  
jobs:
  modules:
    strategy:
      matrix:
        #target: [tf_modules/module1/*, tf_modules/module2/*]
        #target: [awsWorkerIAM/*, awsAnsible*]
        #target: [awsAnsible*]
        #target: [tf_modules/module1/*, tf_modules/module2/*, tf_modules/module3/*]
        #target: [tf_modules/module0/*]
        #target: [tf_modules/module1/*]
        target: [tf_modules/module2/*, tf_modules/module3/*]
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/tf2reusable.yml
    with:
      terraformPath: ${{ matrix.target }}
      tf_typ: ${{ inputs.tf_typ }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    
